name: deploy

on:
  push:
    branches:
      - react-version

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.9.0'
      - name: Build web-app
        run: |
          scl_source enable devtoolset-7 || true
          scl_source enable llvm-toolset-6.0 || true
          /etc/profile.d/modules.sh || true
          module load mpi
          $INSTALL_DIR/bin/thisbdm.sh
          git config --system user.name "Test User"
          git config --system user.email user@test.com
          xvfb-run -d -s "-screen 0 2560x1440x24" make run-demos
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build